default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "compensation_dev") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "compensation_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "compensation_production") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
